"""empty message

Revision ID: 0e866a1a361b
Revises: 237bf7c547cd
Create Date: 2025-05-16 20:58:36.993572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e866a1a361b'
down_revision: Union[str, None] = '237bf7c547cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_admin_id_fkey', 'rooms', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('rooms_admin_id_fkey', 'rooms', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###
